// src/emerald/upstream/components/Footer.vue
<script setup lang="ts">
import { computed } from 'vue'
import VisitorInfoCard from '@emerald/components/VisitorInfoCard.vue'
import { useAppStore } from '@emerald/stores/app'

const appStore = useAppStore()
const showIcp = computed(() => appStore.icpEnabled && appStore.icpNumber)
const showPolice = computed(() => appStore.policeEnabled && appStore.policeNumber)
const showFiling = computed(() => showIcp.value || showPolice.value)
</script>

<template>
  <VisitorInfoCard v-if="appStore.visitorInfoCardEnabled" />
  <footer class="w-full sm:flex-row sm:gap-4 max-w-[1280px] mx-auto p-4">
    <div class="flex flex-row items-center justify-between  text-xs text-muted-foreground">
      <div class="flex gap-1 items-center">
        Powered by
        <a href="https://github.com/xiangwan6667/mmwx-probe-sd" target="_blank" rel="noopener noreferrer" class="transition-opacity hover:opacity-80">
          <span class="font-medium text-foreground">MMWX Probe</span>
        </a>
      </div>
      <div class="flex flex-wrap gap-1 items-center">
        Theme by
        <a href="https://github.com/Tokinx/komari-theme-emerald" target="_blank" rel="noopener noreferrer" class="transition-opacity hover:opacity-80">
          <span class="font-medium text-foreground">Komari Emerald</span>
        </a>
      </div>
    </div>

    <div v-if="showFiling" class="flex flex-wrap gap-2 items-center justify-center sm:flex-shrink-0 pb-7">
      <a
        v-if="showIcp" :href="appStore.icpUrl" target="_blank" rel="noopener noreferrer"
        class="transition-opacity hover:opacity-70"
      >
        <span class="text-xs text-muted-foreground">{{ appStore.icpNumber || '' }}</span>
      </a>
      <span v-if="showIcp && showPolice" class="opacity-50 text-xs text-muted-foreground">·</span>
      <template v-if="showPolice">
        <a
          v-if="appStore.policeUrl" :href="appStore.policeUrl" target="_blank" rel="noopener noreferrer"
          class="transition-opacity hover:opacity-70"
        >
          <span class="text-xs text-muted-foreground">{{ appStore.policeNumber || '' }}</span>
        </a>
        <span v-else class="text-xs text-muted-foreground">{{ appStore.policeNumber || '' }}</span>
      </template>
    </div>
  </footer>
</template>

// src/nezhadash/upstream/components/Footer.tsx
// MMWX adaptation (2026-09-30): host integration; see licenses/NezhaDash-NOTICE.md.
// import { fetchSetting } from "@/lib/nezha-api"
// import { useQuery } from "@tanstack/react-query"
import React from "react"
import { useTranslation } from "react-i18next"

const Footer: React.FC = () => {
  const { t } = useTranslation()
  const isMac = /macintosh|mac os x/i.test(navigator.userAgent)

  // const { data: settingData } = useQuery({
  //   queryKey: ["setting"],
  //   queryFn: () => fetchSetting(),
  //   refetchOnMount: true,
  //   refetchOnWindowFocus: true,
  // })

  return (
    <footer className="mx-auto w-full max-w-5xl px-4 lg:px-0 pb-4 server-footer">
      <section className="flex flex-col">
        <section className="mt-1 flex items-center sm:flex-row flex-col justify-between gap-2 text-[13px] font-light tracking-tight text-neutral-600/50 dark:text-neutral-300/50 server-footer-name">
          <div className="flex items-center gap-1">
            <p>Powered by <a href={"https://github.com/mmwx-group/mmwx-probe"} target="_blank">MMWX Group</a></p>
          </div>
          <div className="server-footer-theme flex flex-col items-center sm:items-end">
            <p className="mt-1 text-[13px] font-light tracking-tight text-neutral-600/50 dark:text-neutral-300/50">
              <kbd className="pointer-events-none mx-1 inline-flex h-4 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium text-muted-foreground opacity-100">
                {isMac ? <span className="text-xs">⌘</span> : "Ctrl "}K
              </kbd>
            </p>
            <section>
              {t("footer.themeBy")}
              <a href={"https://github.com/BITJEBE/nezha-BITJEBE"} target="_blank">
                nezha-BITJEBE
              </a>
            </section>
          </div>
        </section>
      </section>
    </footer>
  )
}

export default Footer
